name: RezDev
description: A Flutter full-stack top-up app with Firebase backend.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  firebase_messaging: ^15.0.0
  google_sign_in: ^6.2.1
  flutter_riverpod: ^2.5.1
  flutter_dotenv: ^5.1.0
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0