
name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter (Channel Master)
        uses: subosito/flutter-action@v2
        with:
          channel: master

      - name: Check Flutter & Dart Version
        run: |
          flutter --version
          dart --version

      - name: Clean Flutter
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Decode keystore
        run: echo "$KEYSTORE_BASE64" | base64 -d > android/app/release-key.jks

      - name: Setup key.properties
        run: |
          echo "storePassword=$STORE_PASSWORD" > android/app/key.properties
          echo "keyPassword=$KEY_PASSWORD" >> android/app/key.properties
          echo "keyAlias=$KEY_ALIAS" >> android/app/key.properties
          echo "storeFile=android/app/release-key.jks" >> android/app/key.properties

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
